---
  swagger: "2.0"
  info:
    title: "play-java-yet-another-example"
    description: "Yet another java play framework example"
  consumes:
    - application/json
  produces:
    - application/json